#!/bin/sh
### BEGIN INIT INFO
# Provides:          mitzon
# Default-Start:     1 2 3 4 5
# Short-Description: Starts mitainesoft mitzon
# Description:       Starts mitainesoft mitzon
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

MITAINEMITZONHOME=/opt/mitainesoft/mitzon
MITAINE_MITZON_PROC=`ps -ef | grep /opt/mitainesoft/mitzon/MitzonBackend/mitzonURLCmdProcessor.py | grep -v vi  | grep -v grep | awk '{print $2}'`

do_start () {
	exec sudo -u mitainesoft /opt/mitainesoft/mitzon/watchdog_mitaine_mitzon.bash
}

do_status () {
	MITAINE_MITZON_PROC=`ps -ef | grep /opt/mitainesoft/mitzon/MitzonBackend/mitzonURLCmdProcessor.py | grep -v vi  | grep -v grep | awk '{print $2}'`
	if [ -n "$MITAINE_MITZON_PROC" ]
	then
   		echo "Mitainesoft Garage Running :) PID='$MITAINE_MITZON_PROC'"
	else
   		echo "Mitainesoft Garage NOT Running :("
	fi

	/opt/vc/bin/vcgencmd measure_temp

    cat /opt/mitainesoft/mitzon/build_info.txt

}

case "$1" in
  start)
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	if [ -n "$MITAINE_MITZON_PROC" ]
	then
   		echo "Mitainesoft stopping... PID='$MITAINE_MITZON_PROC'"
   		kill $MITAINE_MITZON_PROC 2&>1
   		kill -9 $MITAINE_MITZON_PROC 2&>1
	else
   		echo "Mitainesoft Garage already NOT Running..."
   		exit 6
	fi
	echo "Process will restart unless comment out the launch in mitainesoft crontab!  "
	exit 4
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: mitzon [start|stop|status]" >&2
	exit 3
	;;
esac

:
